apiVersion: v2
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
  namespace: nginx-test-2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd:2.4.46
          ports:
            - containerPort: 80
